FROM node:24-alpine

COPY package.json /package.json
COPY server.dev.js /server.dev.js
RUN npm install --ignore-scripts

COPY docker/entrypoint.dev.sh /entrypoint.dev.sh
RUN chmod +x /entrypoint.dev.sh

EXPOSE 8080

ENTRYPOINT ["/entrypoint.dev.sh"]